---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

This website includes analyses to assess the performance of *mr.mash*.

Results for meeting on 03/30/2020.

+ [Assessment of prediction accuracy.](results_accuracy.html)
+ [Assessment of convergence.](results_convergence.html)

Results for meeting on 04/16/2020. Assessment of prediction accuracy and run time of *mr.mash* with different options in the following simulation scenarios:

+ [Independent predictors, shared effects, lowly correlated residuals.](results_indepX_lowcorrV_sharedB_OLD.html)
+ [Independent predictors, independent effects, lowly correlated residuals.](results_indepX_lowcorrV_indepB_OLD.html)
+ [Correlated predictors, shared effects, lowly correlated residuals.](results_corrX_lowcorrV_sharedB_OLD.html)
+ [Correlated predictors, independent effects, lowly correlated residuals.](results_corrX_lowcorrV_indepB_OLD.html)

Results for meeting on 04/30/2020. Assessment of prediction accuracy and run time of *mr.mash* with different options in the following simulation scenarios:

+ [Independent predictors, shared effects, lowly correlated residuals.](results_indepX_lowcorrV_sharedB.html)
+ [Independent predictors, independent effects, lowly correlated residuals.](results_indepX_lowcorrV_indepB.html)
+ [Correlated predictors, shared effects, lowly correlated residuals.](results_corrX_lowcorrV_sharedB.html)
+ [Correlated predictors, independent effects, lowly correlated residuals.](results_corrX_lowcorrV_indepB.html)
+ [Highly correlated predictors, shared effects, lowly correlated residuals.](results_highcorrX_lowcorrV_sharedB.html)
+ [Highly correlated predictors, independent effects, lowly correlated residuals.](results_highcorrX_lowcorrV_indepB.html)

Results for meeting on 05/27/2020. Assessment of prediction accuracy and run time of *mr.mash* with different options against the multivariate versions of LASSO, Elastic Net, and Ridge regression in the following simulation scenarios:

+ [Independent predictors, shared effects, lowly correlated residuals.](results_indepX_lowcorrV_sharedB_05_18_20.html)
+ [Independent predictors, independent effects, lowly correlated residuals.](results_indepX_lowcorrV_indepB_05_18_20.html)
+ [Correlated predictors, shared effects, lowly correlated residuals.](results_corrX_lowcorrV_sharedB_05_18_20.html)
+ [Correlated predictors, independent effects, lowly correlated residuals.](results_corrX_lowcorrV_indepB_05_18_20.html)
+ [Highly correlated predictors, shared effects, lowly correlated residuals.](results_highcorrX_lowcorrV_sharedB_05_18_20.html)
+ [Highly correlated predictors, independent effects, lowly correlated residuals.](results_highcorrX_lowcorrV_indepB_05_18_20.html)
+ [Case study with only two causal responses out of five total.](two_active_responses_issue.html)

Results for meeting on 09/29/2020. Assessment of prediction accuracy and run time of *mr.mash* with different prior specifications against the multivariate versions of LASSO, Elastic Net, and Ridge regression in GTEx-like scenarios:

+ [Three scenarios for predictors correlation, two blocks of responses (shared effects within block), independent residuals.](results_mvreg_all_genes_prior_allscenariosX_indepV_sharedB_2blocksr10.html)
+ [Independent predictors, three causal responses (shared effects) out of ten, independent residuals.](results_mvreg_all_genes_prior_allscenariosX_indepV_sharedB_3causalrespr10.html)

Results for meeting on 10/23/2020. Assessment of prediction accuracy and run time of *mr.mash* with different prior specifications against the multivariate version of LASSO, UTMOST, and univariate Elastic Net in simulations based on GTEx v8 genotypes:

+ [One causal response out of ten, independent residuals.](results_mvreg_all_genes_prior_GTExrealX_indepV_B_1causalrespr10.html)
+ [Three causal responses (with shared effects) out of ten, independent residuals.](results_mvreg_all_genes_prior_GTExrealX_indepV_sharedB_3causalrespr10.html)
+ [Two blocks of responses (shared effects within block), independent residuals.](results_mvreg_all_genes_prior_GTExrealX_indepV_sharedB_2blocksr10.html)
+ [Shared effects, independent residuals.](results_mvreg_all_genes_prior_GTExrealX_indepV_sharedB_r10.html)
+ [Indpendent effects, independent residuals.](results_mvreg_all_genes_prior_GTExrealX_indepV_indepB_r10.html)

Results for meeting on 01/08/2021 (updated on 04/29/2021 after fixing seed issue in DSC and genotypes/expression issues in the rds files). Assessment of prediction accuracy and run time of *mr.mash* with different prior specifications against the multivariate version of LASSO, UTMOST, and univariate Elastic Net in simulations based on GTEx v8 genotypes with truly independent replicates:

+ [One causal response out of ten, independent residuals.](results_mvreg_all_genes_prior_GTExrealX_indepV_B_1causalrespr10_indepReps.html)
+ [Three causal responses (with shared effects) out of ten, independent residuals.](results_mvreg_all_genes_prior_GTExrealX_indepV_sharedB_3causalrespr10_indepReps.html)
+ [Two blocks of responses (shared effects within block), independent residuals.](results_mvreg_all_genes_prior_GTExrealX_indepV_sharedB_2blocksr10_indepReps.html)
+ [Shared effects, independent residuals.](results_mvreg_all_genes_prior_GTExrealX_indepV_sharedB_r10_indepReps.html)
+ [Indpendent effects, independent residuals.](results_mvreg_all_genes_prior_GTExrealX_indepV_indepB_r10_indepReps.html)

Results for meeting on 03/29/2021 (updated on 04/20/2021 after fixing seed issue in DSC and genotypes/expression issues in the rds files). Assessment of prediction accuracy and run time of *mr.mash* with different prior specifications against UTMOST, and univariate Elastic Net in simulations based on GTEx v8 genotypes with truly independent replicates and missing values in Y:

+ [One causal response out of ten, independent residuals.](results_mvreg_all_genes_prior_GTExrealX_indepV_B_1causalrespr10_indepReps_missing_Y.html)
+ [Three causal responses (with shared effects) out of ten, independent residuals.](results_mvreg_all_genes_prior_GTExrealX_indepV_sharedB_3causalrespr10_indepReps_missing_Y.html)
+ [Two blocks of responses (shared effects within block), independent residuals.](results_mvreg_all_genes_prior_GTExrealX_indepV_sharedB_2blocksr10_indepReps_missing_Y.html)
+ [Shared effects, independent residuals.](results_mvreg_all_genes_prior_GTExrealX_indepV_sharedB_r10_indepReps_missing_Y.html)
+ [Indpendent effects, independent residuals.](results_mvreg_all_genes_prior_GTExrealX_indepV_indepB_r10_indepReps_missing_Y.html)



Other investigations:

+ [Case study with dense scenarios.](dense_scenario_issue.html)
+ [Case study with dense scenarios and larger sample size.](dense_scenario_issue_larger_sample.html)
+ [Case study with dense scenarios and univariate analysis.](dense_scenario_issue_univariate.html)
+ [*mash* vs *mr.mash*.](mash_vs_mrmash.html)
+ [Case study with only two causal responses out of six total.](two_active_responses_issue_continued.html)
+ [Case study with larger number of conditions.](mrmash_larger_r_issue.html)
+ [Comparison between *mr.mash*, *sparse multi-task lasso*, and *UTMOST*.](mrmash_vs_mtlasso_vs_utmost.html)
