---
title: "GTEx sample sizes by tissue"
author: "Peter Carbonetto"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  workflowr::wflow_html:
    code_folding: none
---

Here we create a small plot to show the tissue sample sizes.

```{r knitr-opts, include=FALSE}
knitr::opts_chunk$set(comment = "#",collapse = TRUE,results = "hold",
                      fig.align = "center",dpi = 120)
```

Load the packages used in the analysis.

```{r load-pkgs, message=FALSE}
library(ggplot2)
library(cowplot)
```

These are the tissues that were included in the *mr.mash* analyses.

```{r tissues}
tissues <-
  c("Brain_Substantia_nigra",
    "Uterus",
    "Brain_Anterior_cingulate_cortex_BA24",
    "Small_Intestine_Terminal_Ileum",
    "Brain_Spinal_cord_cervical_c-1",
    "Brain_Putamen_basal_ganglia",
    "Brain_Hippocampus",
    "Brain_Frontal_Cortex_BA9",
    "Brain_Amygdala",
    "Brain_Hypothalamus",
    "Minor_Salivary_Gland",
    "Brain_Cerebellar_Hemisphere",
    "Brain_Caudate_basal_ganglia",
    "Brain_Nucleus_accumbens_basal_ganglia", 
    "Vagina",
    "Ovary",
    "Artery_Coronary",
    "Prostate",
    "Brain_Cortex",
    "Esophagus_Gastroesophageal_Junction",
    "Spleen",
    "Cells_EBV-transformed_lymphocytes",
    "Adrenal_Gland",
    "Brain_Cerebellum",
    "Colon_Sigmoid",
    "Breast_Mammary_Tissue",
    "Stomach",
    "Colon_Transverse",
    "Heart_Atrial_Appendage",
    "Artery_Aorta",
    "Pituitary",
    "Esophagus_Muscularis",
    "Adipose_Visceral_Omentum",
    "Heart_Left_Ventricle",
    "Skin_Not_Sun_Exposed_Suprapubic",
    "Pancreas",
    "Adipose_Subcutaneous",
    "Liver",
    "Nerve_Tibial",
    "Lung",
    "Esophagus_Mucosa",
    "Skin_Sun_Exposed_Lower_leg",
    "Cells_Cultured_fibroblasts",
    "Artery_Tibial",
    "Thyroid",
    "Muscle_Skeletal",
    "Testis",
    "Whole_Blood")
```

Read in the tissue sample sizes:

```{r read-data} 
dat <- read.csv("data/gtex-v8-sample-size-by-tissue.csv",
                stringsAsFactors = FALSE)
```

These are the tissue sample sizes:

```{r print-sample-sizes}
rownames(dat) <- dat$Tissue
dat <- dat[tissues,c("Tissue","RNASeq.and.Genotyped.samples")]
names(dat) <- c("tissue","sample_size")
print(dat,row.names = FALSE)
```

Scale the area of the circles in the plot by the sample size of each
tissue:

```{r plot-sample-sizes, fig.height=2, fig.width=7}
n <- nrow(dat)
p <- ggplot(dat,aes(x = 1:n,y = 1,size = sqrt(sample_size))) +
  geom_point(shape = 21,fill = "black",color = "white") +
  scale_x_continuous(breaks = 1:n) +
  scale_size_continuous(range = c(1,6),breaks = sqrt(c(125,200,400,700))) +
  theme_cowplot(font_size = 10)
print(p)
ggsave("sample_sizes.eps",p,height = 2,width = 7)
```
